apiVersion: v2
name: umbrella-chart
description: A Helm chart for Kubernetes


type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:

- name: kube-prometheus-stack
  version: 59.1.0
  repository: https://prometheus-community.github.io/helm-charts

- name: loki-stack
  version: 2.10.2
  repository: https://grafana.github.io/helm-charts

- name: vault
  version: 0.28.0
  repository: https://helm.releases.hashicorp.com
