apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  # annotations:
  #   argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  # syncPolicy:
  #   syncOptions:
  #   - Replace=true
  source:
    path: umbrella-chart
    repoURL: 'https://github.com/philcz16/app-of-apps'
    targetRevision: HEAD
    helm:
      valuesFiles:
        - loki.yaml
  sources: []
  project: default
